-- CREATE SCHEMA sgeu AUTHORIZATION pwusr;

CREATE TABLE TITULACION
(
    CodTit INT PRIMARY KEY,
    NombreTit VARCHAR(100) NOT NULL
);

CREATE TABLE ASIGNATURA
(
    Tit INT NOT NULL,
    CodAsig INT NOT NULL,
    NombreAsig VARCHAR(100) NOT NULL,
    NumGrupos INT NOT NULL CHECK (NumGrupos > 0 AND NumGrupos < 100),
    PRIMARY KEY(Tit, CodAsig),
    FOREIGN KEY(Tit) REFERENCES TITULACION(CodTit)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROFESOR
(
    CodProf INT PRIMARY KEY,
    NombreProf VARCHAR(100) NOT NULL,
    ApellidosProf VARCHAR(100) NOT NULL
);

CREATE TABLE PROFESOR_ASIGNATURA
(
    CodProf INT NOT NULL,
    CodTit INT NOT NULL,
    CodAsig INT NOT NULL,
    PRIMARY KEY(CodProf, CodTit, CodAsig),
    FOREIGN KEY(CodProf) REFERENCES PROFESOR(CodProf)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(CodTit, CodAsig) REFERENCES ASIGNATURA(Tit,CodAsig)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ENCUESTA
(
    IdEnc INT NOT NULL AUTO_INCREMENT,
    Descripcion VARCHAR(120) NOT NULL,
    Instrucciones VARCHAR(500) NOT NULL,
    IsDeleted BIT(1) NOT NULL,
    PRIMARY KEY(IdEnc)
);

CREATE TABLE CATEGORIA
(
    IdCat INT NOT NULL AUTO_INCREMENT,
    NombreCat VARCHAR(100) NOT NULL,
    IsDeleted BIT(1) NOT NULL,
    PRIMARY KEY(IdCat),
    UNIQUE(NombreCat)
);

CREATE TABLE SUBCATEGORIA
(
    IdSub INT NOT NULL AUTO_INCREMENT,
    NombreSub VARCHAR(100) NOT NULL,
    Categoria INT NOT NULL,
    IsDeleted BIT(1) NOT NULL,
    PRIMARY KEY(IdSub),
    FOREIGN KEY(Categoria) REFERENCES CATEGORIA(IdCat)
        ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE(NombreSub)
);

CREATE TABLE PREGUNTA
(
    IdPreg INT NOT NULL AUTO_INCREMENT,
    Enunciado VARCHAR(300) NOT NULL,
    Encuesta INT NOT NULL,
    RelacionProfesor BIT(1) NOT NULL,
    Subcategoria INT NOT NULL,
    Categoria INT NOT NULL,
    IsDeleted BIT(1) NOT NULL,
    PRIMARY KEY(IdPreg),
    FOREIGN KEY(Encuesta) REFERENCES ENCUESTA(IdEnc)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(Subcategoria) REFERENCES SUBCATEGORIA(IdSub)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(Categoria) REFERENCES CATEGORIA(IdCat)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OPCION
(
    IdOp INT NOT NULL AUTO_INCREMENT,
    Texto VARCHAR(50) NOT NULL,
    Pregunta INT NOT NULL,
    IsDeleted BIT(1) NOT NULL,
    PRIMARY KEY(IdOp),
    FOREIGN KEY(Pregunta) REFERENCES PREGUNTA(IdPreg)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ENCUESTA_RESP
(
    IdEncresp INT NOT NULL AUTO_INCREMENT,
    Titulacion INT NOT NULL,
    Asignatura INT NOT NULL,
    Encuesta INT NOT NULL,
    Grupo INT NOT NULL CHECK (Grupo > 0 AND Grupo < 100),
    PRIMARY KEY(IdEncresp),
    FOREIGN KEY(Titulacion, Asignatura) REFERENCES ASIGNATURA(Tit,CodAsig)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY(Encuesta) REFERENCES ENCUESTA(IdEnc)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE RESPUESTAS
(
    IdEncresp INT NOT NULL,
    IdResp INT NOT NULL AUTO_INCREMENT,
    Opcion INT NOT NULL,
    Pregunta INT NOT NULL,
    PRIMARY KEY(IdResp),
    FOREIGN KEY(IdEncresp) REFERENCES ENCUESTA_RESP(IdEncresp)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY(Opcion) REFERENCES OPCION(IdOp)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY(Pregunta) REFERENCES PREGUNTA(IdPreg)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

