CREATE TABLE USUARIOS
(
    IdUsr INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE, 
    Email VARCHAR(100) NOT NULL UNIQUE,
    Nombre VARCHAR(100) NOT NULL,
    Pass VARCHAR(100) NOT NULL,
    Estado BIT(1) NOT NULL
);
